% This function merges caret paint files and create the new piant files
function file_to_write=create_caret_multicolumns_paints(file_name,node,electleeds)
pp={'BeginHeader' ...
'Caret-Version 5.65' ...
'Date ' num2str(date) ...
'comment 	' ...
'encoding ASCII'...
'EndHeader'...
'tag-version 1'...
'tag-number-of-nodes 163842'...
'tag-number-of-columns 1'...
'tag-title  Electode_multi_column' ...
['tag-number-of-paint-names ' num2str(size(electleeds,2)+1)] ...
'tag-column-name  0' ...
'tag-column-comment'...
'tag-BEGIN-DATA'...
'0 ???'};

pp{10}=['tag-number-of-columns ' num2str(size(node,2))];

n=size(pp,2);

file_to_write=file_name;

final_node=[[0:size(node,1)-1]', node];
fid=fopen(file_to_write,'w');
for i=1:n
     fprintf(fid,[ pp{i} '\n']);
end
for i=1:size(electleeds,2)
     fprintf(fid,[ electleeds{i} '\n']);
end
dlmwrite(file_to_write, final_node, '-append','roffset', 0, 'delimiter', ' ','precision', 6); % adding noddes data to file
fclose(fid);

    


